services:

  # postgis:
  #   image: postgis/postgis
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #   # volumes:
  #   #   - ./db/temp_create_table.sql:/docker-entrypoint-initdb.d/temp_create_table.sql

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - ./db/temp_create_table.sql:/docker-entrypoint-initdb.d/temp_create_table.sql
    ports:
      - 5433:5432

  backend:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - "8000:8000"
      networks:
        my_network:

networks:
  my_network: