"""db init

Revision ID: 4d048d48bf88
Revises: 7ed98121c554
Create Date: 2024-05-16 21:30:06.252297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d048d48bf88'
down_revision: Union[str, None] = '7ed98121c554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uprofile',
    sa.Column('first_name', sa.String(length=124), nullable=False),
    sa.Column('last_name', sa.String(length=124), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['customuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('customuser', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('customuser', sa.Column('role', sa.Enum('user', 'manager', 'admin', 'owner', name='userrole'), nullable=False))
    op.alter_column('customuser', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=324),
               existing_nullable=False)
    op.create_unique_constraint('uq_email', 'customuser', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email', 'customuser', type_='unique')
    op.alter_column('customuser', 'email',
               existing_type=sa.String(length=324),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    op.drop_column('customuser', 'role')
    op.drop_column('customuser', 'username')
    op.drop_table('uprofile')
    # ### end Alembic commands ###
