"""Init first db tables

Revision ID: 7ed98121c554
Revises: 
Create Date: 2024-05-10 17:56:45.684837

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ed98121c554'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=False),
    sa.Column('datetime_start', sa.DATE(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('latitude_start', sa.FLOAT(), nullable=True),
    sa.Column('longitude_start', sa.FLOAT(), nullable=True),
    sa.Column('actual_route_length', sa.FLOAT(), nullable=True),
    sa.Column('gps_file', sa.JSON(), nullable=True),
    sa.CheckConstraint('LENGTH(author) >= 7 AND LENGTH(author) <= 255', name='check_author_length'),
    sa.CheckConstraint('LENGTH(description) >= 30 AND LENGTH(description) <= 10000', name='check_description_length'),
    sa.CheckConstraint('LENGTH(name) >= 7 AND LENGTH(name) <= 255', name='check_name_length'),
    sa.CheckConstraint('actual_route_length > 0 AND actual_route_length <= 200000', name='check_actual_route_length_range'),
    sa.CheckConstraint('latitude_start >= -90 AND latitude_start <= 90', name='check_latitude_start_range'),
    sa.CheckConstraint('longitude_start >= -180 AND longitude_start <= 180', name='check_longitude_start_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'author', 'datetime_start', name='uq_track')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track')
    op.drop_table('customuser')
    # ### end Alembic commands ###
