name: Track app workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  tests:
    runs-on: ubuntu-latest
    name: Lint and Pytest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.*"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./requirements/dev.txt
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "src"
          args: "--config setup.cfg"
      - name: isort
        uses: isort/isort-action@master
        with:
          configuration: .setup.cfg
  